### PR TITLE
Added RFC for digsrc digcap

### PR DESCRIPTION
**Pull request by pderouen**
[Read the RFC here](https://github.com/pderouen/rfcs/blob/master/text/0000-abstract-digsrc-digcap-support.md)

### CODE REVIEW

**Comment by ginty** [comment]
@pderouen can you clean up the markdown a bit, its hard to read right now.
Generally don't use # unless you want generate a heading and generate code blocks like this:

    ~~~ruby
    def blah
    end
    ~~~

**Comment by pderouen** [comment]
@ginty is that better?

**Comment by ginty** [comment]
Hi @pderouen, generally this looks good and is definitely required, thanks for submitting it.

In this example:

~~~
instruments = {
        (spimosi):DigSrc 1;
}
...
-- here comes a bit
((spimosi):DigSrc = SEND)                                                                       
                > tp0   000DXXXX ;
repeat 39       > tp0   000DXXXX ;
repeat 40       > tp0   100DLXXX ;
-- here comes the next bit
((spimosi):DigSrc = SEND)                                                                       
                > tp0   000DXXXX ;
repeat 39       > tp0   000DXXXX ;
repeat 40       > tp0   100DLXXX ;
~~~

I guess the SEND means update whatever 'D' is pointing to with the next value in the data source.

For the size, I'm wondering if we need to implicitly declare it as in your API, or can it not be deduced based on what you are driving?

Say we had these pins:

~~~ruby
add_pin :tdi
add_pins :portA, size: 8
~~~

Then could the size not be inferred when you are driving it?

~~~ruby
pin(:tdi).drive          # Origen knows you are driving with size 1 here
pin(:portA).drive        # 8 here
pin(:portA)[3..0].drive  # and 4 here

**Comment by pderouen** [comment]
You understanding is correct.  With digsrc pin data of "D" means that the drive value is defined by the digsrc memory.  The SEND means advance to the next memory location.  When digsrc isn't controlling the pin, the pin data looks normal ("1", "0" etc).

Perhaps the size information doesn't need to be passed by the protocol driver.  The default could be inferred by the size of the pin group being captured.  But, you can load up to a 32-bit wide value to be serially shifted in.  We do this frequently (it's more efficient test time wise and less cumbersome to code). I might need to specify the width from my pattern source.

**Comment by ginty** [comment]
I think an equivalent of push_microcode for headers should come out of this, but I don't think the default solution we come up with here should require an application to use it. So I would like to get rid of the tester.instrument_setting requirement in the current proposal.
Essentially, it is the goal of Origen to abstract and deal with low level tester concepts like digsrc/cap so that the user doesn't need to worry about how to set it up, at least at the pattern level.

Generally I think digsrc should be the default way of doing overlays on the UltraFLEX, I'm not sure if there is ever a real reason you would want to it the J750 way?
In one of our apps we are doing old-style overlays on the UltraFLEX, but that was just because at the time we didn't have the experience of how digsrc worked and so it was an easier conversion from J750. However, if Origen had just dealt with translating everything to digsrc that would have been much better.

Anyway, the JTAG driver implements overlays like this today:

~~~ruby
if options[:no_subr]
  Origen.tester.dont_compress = true
  if reg_or_val[i].overlay_str != last_overlay_label
    $tester.label(reg_or_val[i].overlay_str)
    last_overlay_label = reg_or_val[i].overlay_str
  end
  owner.pin(:tdo).assert(reg_or_val[i] ? reg_or_val[i] : 0)
else
  call_subroutine = reg_or_val[i].overlay_str
end
~~~

So it implements two styles of doing overlays, based on the J750, and this is clearly the wrong way of going about it because we can't easily implement alternative ATE implementations without updating all the driver code.

I would propose this instead:

~~~ruby
tester.cycle   # Actually generate the drive cycle, whether or not we are going to overlay

if reg_or_val[i].has_overlay?
  options[:pins] = dut.pin(:tdi)
  tester.overlay reg_or_val[i].overlay_str, options
end
~~~

The new tester overlay method would now modify the last vector and/or inject additional vectors/code to do things like the SEND. Note that the vector generator APIs already provide the ability to inject new vectors/code into the stack at position -1, -2, etc.

In terms of the UF implementation, it would know from the supplied pin argument what pins/size it was overlaying and it would keep track of these. That would then be used to render the required instrument header at the end.
It would also just throw away the overlay string when configured for digsrc style overlays (should be the default as discussed), or it would use it when configured to do the old-style overlays.

The type of overlay you generate would be controlled by the application like this:

~~~ruby
tester.overlay_style = :subroutine
tester.overlay_style = :label 
tester.overlay_style = :digsrc
~~~

This approach seems to have much less API surface area than the current proposal, and keeps things pretty simple at the protocol driver level which is welcome. The tester driver then picks up all of the heavy lifting for the vector manipulation side of things, and from an application perspective they can use the exact same code to create subroutine overlays on the J750 and digsrc overlays on the UF.

**Comment by pderouen** [comment]
@ginty, I like this better.  It's a cleaner way of doing business.  Yes, there are times when vector modify would be used on the UFlex instead of digsrc.  It's rare.  But, we do use it.  2 cases I can think of: Poor job of channel assignment can prevent you from using unique data per site.  Also, digsrc memory setup incurs a pattern start penalty.  So, when only a small amount of pin data is being changed vector modify is faster.

There is still a need for my app to have the option of specifying bit width though.  Could that be a part of .overlay_style somehow?  We have a cases (more often than not) when we want to change it.  For example, we have patterns that use the Nexus debug interface that are used to dump memory blocks through JTAG.  We overlay the address on TDI and capture data on TDO.  But, we configure TDI as a 32 bit, serial, LSB first digsrc instrument and TDO as an 8-bit, serial LSB first, type long digcap isntrument.  While it would work if they were 1-bit instruments, the test time penalty for loading and reading from the DSSC memory would multiply by 32x and 8x respectively.  The digsrc / digcap instrument handles the serialization/de-serialization (if you define the instrument accordingly).

...Then, there's also the need to get the digsrc start microcode inserted at the minimum cycle distance before any send microcode.

**Comment by ginty** [comment]
Hi @pderouen, I think I've mis-understood what the size here means, I was thinking that it meant this:

~~~text
// Size == 1
0 0 1 0 1111 0
0 0 D 0 1111 0

// Size == 4
0 0 1 0 1111 0
0 0 1 0 DDDD 0
~~~

However, I see now that it is more to do with how the source/capture memory is organized on the tester, so not something that Origen can really know about and work out on the fly.

93K has the same concept btw, but you don't have to include that info in the pattern.

I still think the user shouldn't need to worry about the microcode formatting, so we should do it via an API rather than via a header equivalent of push_microcode.
That also leaves the option open to re-use the same API on a future tester with the similar concept and requirement.

I haven't given too much thought to this, but just as an example:

~~~ruby
tester.source_memory do |mem|
  mem.pin :tdi, size: 32
end

tester.capture_memory do |mem|
  mem.pin :tdo, size: 8, bit_order: :msb0  # LSB first should be default, aligns to register default (I think!)
  mem.pin :blah # ...
end
~~~

By default the memory size should be set to 1, so that Origen can generate syntactically correct patterns if you don't call this.

You should be able to call that configuration for every pattern, whether you actually use the instrument or not. The tester will know from the overlay method being called if it has been used and on what pins, so it can dynamically update the header as required.

For the digsrc start microcode, I think the new tester overlay method will be able to do that pretty easily:

~~~ruby
if overlay_style == :digsrc
  unless @digsrc_started
    microcode "digsrc(start)", offset: -144
    @digsrc_started = true
  end
  # Implementation of the overlay here
end
~~~

That would insert it 144 vectors before the current vector, which would guarantee at least 144 cycles, but quite possibly more, which I assume is ok?
The final implementation would probably want to check we had encountered at least 144 vectors by this point and if not insert it at the beginning, or would we just keep it simple and always insert it at the beginning anyway?
I think there is a method you can call to find out how many cycles there has been so far, so you could have it raise an error in the event of it being < 144 and prompt the user that they need to add some padding before they can use digsrc.

**Comment by pderouen** [comment]
@ginty, I love it.  This is perfect.

**Comment by pderouen** [comment]
@ginty, I incorporated your feedback (and tester.capture_style - needed?)

**Comment by pderouen** [comment]
@redxeth, want to weigh in?

**Comment by ginty** [comment]
Hi @pderouen,

The latest version looks good, just a few comments:

I think MTO should be implemented as another overlay/capture style, don't really like the current implementation that uses MTO specific APIs (they would continue to be supported for legacy compatibility, but this new style approach would be the recommended way).

Definitely I think tester.capture_style_is needed.

I wonder if we would need to be able to independently configure difference source memories, should we add an identifier like this?

~~~ruby
tester.source_memory :digsrc do |mem|
  mem.pin :tdi, size:32
end

# If no memory ID given, it would populate a :default configuration internally, the generator 
# would fall back to this if no memory-type-specific configuration has been given
test.source_memory do |mem|
  mem.pin :tdi, size: 8
end
~~~

_tester.overlay will need to be able to handle a drive bit being spread across multiple cycles._

Sounds like we need a way for the driver to indicate to the tester generator when a change of data bit is occurring:

~~~ruby
tester.cycle
if reg_or_val[i].has_overlay?
  options[:pins] = dut.pin(:tdi)   # Tell the tester which pins to overlay
  tester.overlay reg_or_val[i].overlay_str, options
  #...
  # Same data, but need it on multiple cycles
  tester.cycle
  options[:change_data] = false
  tester.overlay reg_or_val[i].overlay_str, options
end
~~~

By default, it would assume that it should move to the next data item when overlay is called, that would generate the SEND microcode in the digsrc case.
When called with the change_data = false switch, it would drive the same data, which means it would inhibit the SEND microcode and just update the pin states.

**Comment by pderouen** [comment]
Incorporated feedback

**Comment by ginty** [comment]
@pderouen, are you planning to work on the implementation for this?

From my pov, we can approve this and go to implementation whenever you like.

**Comment by pderouen** [comment]
@ginty, I'm certainly willing to be the one to work on this.  But, maybe it's better to wait another few weeks for any other feedback before getting started.  I wouldn't be able start sooner than that anyway.

**Comment by pderouen** [comment]
I've started a branch of origen_testers, working on the uflex implmentation:
https://github.com/Origen-SDK/origen_testers/compare/rfc2

**Comment by redxeth** [comment]
Sorry for late weigh-in:  
I think that overlay_style has 2 facets to it:

-	VecEdit  vs DigSrc (if tester has dig src)
-	Subr (if tester supports it) vs label (in main pattern)

One is whether you want to modify vectors in main or subr and one is HOW you want to modify those vectors.

The update should by assume vecedit and subr by default for these option types.

So something like:
$tester.overlay_style (:subr, :label)
$tester.overlay_method(:vecedit, :digsrc)

Or the reverse-- I would just like to see all 4 possibilities for 'overlay' be implemented (I can help).

**Comment by pderouen** [comment]
@redxeth, how about all 4 possibilities like this:
:label, :subroutine, :digsrc, :digsrc_subroutine

**Comment by pderouen** [comment]
@redxeth,  after the discussion earlier today I decided to provide the option to override the global overlay_style to make backward compatibility easier to implement.
~~~ruby
  tester.overlay_style = :subroutine
  # etc. etc.
  # now inside the driver, the call to overlay can override the overlay_style
  tester.overlay dut.pin(:tdi), overlay_style: :label 
~~~

**Comment by redxeth** [comment]
@pderouen I guess.   To me they are 2 separate things, but up to you, 4 values on 1 parameter is the same I guess as 2 values each on 2 parameters.  Now unless we add a third...

**Comment by ginty** [comment]
I find the single parameter more intuitive tbh, I envision a nice doc page once we are done which shows a clear example of what you get by selecting style x, y, z, etc.

**Comment by ginty** [comment]
Also it may not be clear (and may be influencing some of your thinking @redxeth), but I expect the choice of overlay_style to be largely tester-specific. i.e. there is no expectation that the 4 options currently on the table will map directly to other platforms. For example, V93K might have only 2 options, called something completely different.

In most cases I expect the choice of style you want on a particular platform to apply to all of your patterns, so it would be set in a single place like the the target and I don't envisage apps to require a whole lot of tester type branching to handle overlays.

And while we have the discussion open again, ultimately (i.e. not required for the first version of this) it would be cool if by selecting the :subroutine style it would automatically create the subroutine pattern for you instead of having to manually do it like today. That should definitely be possible since between the driver and tester they will know what that should look like.

**Comment by pderouen** [comment]
@ginty, funny that you mention auto-creation of the subroutine.  @redxeth had the same thought yesterday.  I just "finished" with the subroutine method.  It simply deletes the most recently generated cycle when overlay is requested.  Could easily just move it to a different stage object that is marked with the requested subroutine name...  I wouldn't know what to do with it after that though.

**Comment by ginty** [comment]
@pderouen, cool.
If you are inclined to have a go at implementation, here are some rough notes on how I would go about tackling it...

Your tester driver should hopefully be asked to generate every overlay vector, and when the style is set to subroutine it outputs a subroutine call when asked to generate the first overlay vector, and then just throws the rest away.

Instead of throwing them away, I would change the bank (where generated vectors will be stored) to a new one when the overlay starts:

~~~ruby
Origen.generator.stage = subroutine_name
~~~

Then process all vector requests as normal as if they were being included in-line, returning the stage back to normal when you get a vector without the overlay:

~~~ruby
Origen.generator.stage = :body
~~~

So you should then end up with the main pattern as it is today, but with the vectors for the subroutine in the bank.

At the end you would write out the subroutine to a file, here is how Origen does it normally: https://github.com/Origen-SDK/origen/blob/master/lib/origen/generator/pattern.rb#L352

Probably you would add some smarts around that to avoid generating the same overlay multiple times if it is referenced multiple times within the pattern.

**Comment by pderouen** [comment]
I wasn't planning to try to get it into this version.  But, we should think it through now in case adding support requires any fundamental changes to the way tester.overlay is used.  I think that I have convinced myself that it is possible without changing anything.  The tricky part is knowing when the subroutine is completed.  If there are multiple requests to the same overlay subroutine name, the overlay method can detect this when it's checking to see whether the call microcode needs to be inserted.  If the subroutine stage object already has vectors in it and the call needs to be inserted, then the previous overlay must have been completed.

**Comment by pderouen** [comment]
...or, the api could be changed to use tester.cycle.  Instead of this:
~~~ruby
  tester.cycle
  tester.overlay blah, blah if bit.has_overlay?
~~~
Do this:
~~~ruby
  tester.cycle overlay_options_here
~~~

**Comment by redxeth** [comment]
The trick is how to generate a single subroutine file that covers multiple patterns in a generation.  At the individual pattern generation level yes you can output the subroutines you need for overlays, but how to accumulate them?  Maybe each pattern generates <patternname>_subr.atp (in the case of IGXL) and then it is up to the overarching pattern iterator to have to accumulate them together.  

Especially since this subr generation technique could go beyond it's application of overlays-- subroutines are good also for reducing LVM for vectors used repeatedly, even if no run-time modification is done.

Would have to handle being able to generate say 2 subroutine files then, one for overlays and one for more general stuff (like we do today).

**Pull request merged**
