### PR TITLE
Added RFC for Limits File support for 93K.

### PR DESCRIPTION
**Pull request by redxeth**
Initial stages.  I've already started some implementation in my own fork of origen_testers due to project urgency but wanted to go through the proper process here as I'm sure a better solution is there.

Will be implementing the RFC as well (though anyone feel free to help).

[View RFC here](https://github.com/redxeth/rfcs/blob/master/text/0000-v93k-program-integration-updates.md)

### CODE REVIEW

**Comment by ginty** [comment]
Hi @redxeth, on the limits file, I understand that there are various ways of consuming limits files (and probably formatting them I assume, though I am not sure), and that the officially supported one from Advantest is called "testtable".

Can you confirm if the limit file you are proposing to generate here is compatible with that?

**Comment by ginty** [comment]
> Addition of limits file class, similar to variables_file class. Test methods add the limits they require to an instantion of this class.

I think if we are doing this right, we want to get the limits into the ATP/AST representation of the flow. We want to get to the point where the AST contains a complete semantic representation of the flow, but we are not there yet. It already contains bin and test number information, and the flow of course, but it doesn't currently model meta-data for each test like the limits.

Once you get that done, the final rendering is the easy part, and it means that downstream consumers of the AST, like documentation generators, can now start to include the limits.

**Comment by redxeth** [comment]
@ginty Yes it adds to the 'testtable' directory but the intent is mainly to create a CSV file inside a subdir called 'limits' under 'testtable'.  All sub-IP modules each have a CSV in this dir that get imported by a master MFH.  I will update RFC text to include examples of what it will look like.

**Comment by redxeth** [comment]
@ginty Yes an ATP/AST representation would be better sure.  For now I have the test_method class add its limits instance to the master limits_file instance.  Then have the limits_file template go through all test suites and output all that is needed for the limit, namely:

- test suite name
- test number
- pattern name (test name)
- lower limits
- upper limits
- bin info

The problem I quickly encountered when going from my initial test class, however, was that if you generate more than 1 test flow, the list of test suites is reset and so any collection of test suites will not include ALL of them.   The limits file object is complete, however, it does not (currently) contain the test suite specific info necessary (name, number, pattern) since the limits were created from the test_method.  

So will have to change tack now thinking about it to add the limits from test suite somehow so the limits can get that extra info.  Just trying to figure the connection between test suite creation and test method creation (kinda tricky, method_missing based it seems) to ensure that no suites are missed.

**Comment by ginty** [comment]
@redxeth, ok sounds good.
testtable/limits/block.csv seems like a good convention, as part of this RFC I think we should also come up with a better convention for the other files too.
e.g. currently for the flow we use testflow/mfh.testflow.group/block.tf, but I don't really like that group folder name, just seems like bad practice to have '.' in the name.
Could you update the RFC with a proposal based on what your current project does?

**Comment by redxeth** [comment]
@ginty Yep will update.

**Comment by ginty** [comment]
Some of the concern about test_suite vs. test_method will go away under an AST-based approach, there you will just have a test node that will contain all the information about it.

In the flow rendering step, where you would render all flows before doing the limits file at the end, you would walk through the AST and decide whether to render the limits as part of the flow, or to send it to the limits file class to be output later.

So you would instantiate your limits file class and assign it to an @@ variable so that it can be shared between the multiple flows being rendered. Probably you would have @@limits_files be a hash, so that per-flow you could optionally decide to specify a particular resources_filename like you can do with some of the other shared sheets.

**Comment by redxeth** [comment]
Yes, in my implementation the limits file is a @@ variable.  Similar to @@variables_fie it is an array (to permit multiple flows to have unique filenames if they want, otherwise default 'global') of arrays (array called test_limits defined in the limits_file class.  The test_limits array gets the entire test_method limit added like this:

    `test_limits << @limits if $tester.create_limits_file`

As to when to generate, during flow gen is probably fine-- just figured it was the same as @@variables_file which is done at then end with all sheet generators.  To me just having another one there for limits_file just makes sense.

Let me review the AST stuff-- really foreign concept to me at this point-- though I see that there are some reserved methods used (e.g. 'on_test', 'on_job', 'on_flow_flag', etc.)

**Comment by ginty** [comment]
Yep, should definitely have a dedicated limits file class I think.

For the AST, read the docs for the underlying AST gem that ATP uses, particularly the Node and Processor::Mixin sections: http://www.rubydoc.info/gems/ast/AST

Then update the ATP plugin to add an API to create a limit node and anything else you think you might need, after that things should be pretty easy back at OrigenTesters.

**Comment by info-rchitect** [comment]
any idea on when this is going to be implemented?  The reason I ask is because we are just getting started with our levels and other tester resources creation.

**Comment by ginty** [comment]
I think this is still probably a couple of months away or so.

The intention of this RFC though is not to provide new APIs for levels or timing creation. Rather it is to provide a build switch that will cause the V93K program generator to output something that is more typical of how V93K test programs are written by hand.
Specifically, to create a limits sheet with the required linkages to test suites/methods, rather than have the limits attached directly to the test suites.

It is not envisaged that the application side should have to change anything to change over to that style of output, rather it will all be backend changes and the user will just have to flip a switch if they want to change over to this when it is ready.

**Comment by redxeth** [comment]
I very much need external limit file for the project I'm working on within the next month or so!   I am starting up various PR to support the changes I'm making for 93K including one specifically for limits_file generation capability.   

Unfortunately, my limits_file solution only supports a single TF-- but working on updating this to support multiple TF very soon-- will provide option for both unified limits CSV (super-set of all limits for all TF generated) as well as separate CVS per TF, though the former will come sooner than the latter.

Please take a look at my current solution if you like on my fork at [redxeth/origen_testers](https://github.com/redxeth/origen_testers).

Am expecting to kick of these PR this coming week!

**Comment by redxeth** [comment]
@ginty Updated the filename and verbage to be more limits file centric.  Will create separate RFCS files for other desired changes (multiport, smartbuild, pattern compiler).

Please take a look:
- [RFCS TEXT FOLDER](https://github.com/redxeth/rfcs/tree/master/text)
- [RFCS FILE](https://github.com/redxeth/rfcs/blob/master/text/0000-v93k-limits-file-support.md)

**Comment by redxeth** [comment]
BTW the multiple file thing I mention above has been resolved already in the latest in [my origen_testers fork](https://github.com/redxeth/origen_testers) as part of SmartBuild additions.

But I need to clean it up as part of another SmartBuild-centric RFCS PR.

**Pull request merged**
