### PR TITLE
Add import and export to Origen::Model

### PR DESCRIPTION
**Pull request by ginty**
View the RFC here: https://github.com/ginty/rfcs/blob/master/text/0000-model-export-and-import.md

### CODE REVIEW

**Comment by info-rchitect** [comment]
I agree with the concept wholeheartedly.  So does this RFC also handle [this issue](https://github.com/Origen-SDK/origen/issues/96) as well?

The only thing I can think to add is the concept of sub_block aliasing.  In an ideal world, all of the upstream info sources would use the exact same ID for the same IP instance.  Unfortunately that is not always the case.  So the same IP can be referred to as 'ddr1' and 'ddr1_phy', depending on the source.  Is there a way we could build in a way to handle this 'fact of life'?  

~~~ruby
# The application model can then call import during initialization:
module MyApp
  class MyDUT
    include Origen::TopLevel
    
    def initialize(options = {})
      import :device_1, alias: :device_1_phy do |ip|
        ip.import 'pin_data', 
        ip.import 'registers_from_xml'
        ip.import 'test_registers'
      end
    end
  end
end
~~~

**Comment by pderouen** [comment]
~~~
Having an easy and official way to export to Origen format, means that all importers, like those provided by CrossOrigen, can change over to always exporting direct to Origen format so that the conversion from 3rd party format becomes an off-line activity.
~~~
I'm not familiar with CrossOrigen, so this may be a silly question.  How will the off-line export activity be initiated?  Through a command provided by the plug-in?

**Comment by ginty** [comment]
@info-rchitect, thanks for the review.

I don't see this as particularly addressing that issue about a pin schema, but maybe I don't quite understand what you were getting at in that isssue.
As far as pins go, it just means they would follow the same flow as registers:

`pins.xml -> anonymous model -> pins.rb`

It is a good idea to handle sub-block aliases, I would propose we introduce an API that follows the look-and-feel conventions laid down by existing APIs, e.g:

~~~ruby
def initialize(options = {})
  # New method, inspired by add_pin_alias. Need to make sure this is implemented in such a way
  # that it works if the sub-blocks in question haven't actually been instantiated yet
  add_sub_block_alias :alternative_name, :primary_name

  # The import method would check for existing aliases to combine differently named references
  # to the same sub-block into the same Origen object
  import 'device_1_registers_from_xml'
  import 'device_1_test_registers'
end
~~~

**Comment by info-rchitect** [comment]
regarding the pin schema, once the anonymous model is created with a fairly complex example, we could create a pin schema for Origen that would ensure folks don't have to write their own importer from scratch.  but i can see it is not a part of this RFC.

**Comment by ginty** [comment]
@pderouen, that's a good question.

Certainly the most recent importer that I added to CrossOrigen was invoked through a command, effectively:

`origen cr:import path/to/some.xml`

Which would generate a `.rb` that could then be included in the model. They don't all work like that however, but that's the direction we should be going and this RFC is about adding more infrastructure to make it easier for all importers to move in that direction.

Now you asked though, I wonder if the command is the best approach, maybe it should be handled more like [defining a remote](http://origen-sdk.org/origen/guides/misc/remotes/)?

**Comment by info-rchitect** [comment]
@pderouen & @ginty I import over 100 files to find my regs, pins, fuses etc.  How would that work given a command only implementation?

**Comment by rlaj** [comment]
Don't think that's what they were getting at.  Definitely can't be command-only, but implementation should make command-based implementation (at the plugin level) straightforward.

**Comment by rlaj** [comment]
Btw, haven't commented previously by this is an AWESOME rfc!

**Comment by info-rchitect** [comment]
@ginty had asked me to think about picking up this RFC.  I think this might be better to split into multiple RFCs, in this order:

1. convert sub-blocks to lazy instantiation
2. integrate the cross_origen functionality to origen core

IMO, #1 is really best suited for @ginty and I could take up #2 as I did write quite a bit of the cross_origen code.  Thoughts?

**Comment by rlaj** [comment]
bumping this rfc...

Is anyone working on the sub-block lazy instantiation?  Asking for a friend.

**Comment by info-rchitect** [comment]
@rlaj I have offered to handle part #2 of this RFC but not sure I have the RUby chops for #1 to be honest.

**Comment by ginty** [comment]
I'll do the lazy instantiation bit, should be quite soon, planning to pick this up next once I get the current updates I'm doing to ATP/Testers out of the way (this week).

**Pull request merged**
